### ISSUE TITLE
JSON import not working

### ISSUE THREAD

**Issue by zod-melodic** [tmk907/MyTikTokBackup#4]
When selecting a JSON file received from a TikTok data request using Import user data in the Import tab, nothing is found or available for download.

**Comment by tmk907** [comment]
Does it mean that there is: 
0 urls,
0 videos already downloaded,
0 bookmarked videos ready to download?
Are there statistics displayed, such as videos in your browsing history?

**Comment by zod-melodic** [comment]
No statistics are displayed. Nothing changes after selecting the file to import. It continues to read: 
0 urls,
0 videos already downloaded,
0 bookmarked videos ready to download

**Comment by tmk907** [comment]
Maybe TikTok changed format of file with user data. I will request my file and see if it works.
Please check if there are any errors `[ERR]` in logs in folder `%LocalAppData%\Packages\60490polApki.MyTikTokBackup_4j2bpc236qkhp\LocalState`

**Comment by zod-melodic** [comment]
Tried it again. There is nothing marked [ERR], just:

2022-04-03 13:28:23.016 -07:00 [INF] History https://www.tiktok.com/
2022-04-03 13:28:24.822 -07:00 [INF] NavigationCompleted

**Comment by tmk907** [comment]
I downloaded user data and everything works fine. All url are detected and I can download videos. 
I make new release that logs a few more things [https://github.com/tmk907/MyTikTokBackup/releases/download/untagged-3d1bf60436dfdc91efdd/MyTikTokBackup.Desktop.Package._1.1.11.0_x64.msix](https://github.com/tmk907/MyTikTokBackup/releases/download/untagged-3d1bf60436dfdc91efdd/MyTikTokBackup.Desktop.Package._1.1.11.0_x64.msix)
Please install it and check if there are any errors in logs

**Comment by zod-melodic** [comment]
The link isn't working for me. Gives me a 404.

**Comment by tmk907** [comment]
[https://github.com/tmk907/MyTikTokBackup/releases/download/v1.1.11/MyTikTokBackup.Desktop.Package._1.1.11.0_x64.msix](https://github.com/tmk907/MyTikTokBackup/releases/download/v1.1.11/MyTikTokBackup.Desktop.Package._1.1.11.0_x64.msix)

**Comment by zod-melodic** [comment]
022-04-10 11:15:03.920 -07:00 [INF] History https://www.tiktok.com/
2022-04-10 11:15:07.573 -07:00 [ERR] Can't deserialize user data System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.Profile['Profile Information'].ProfileMap.PlatformInfo[0] | LineNumber: 561754 | BytePositionInLine: 11.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'StartObject' as a string.
   at System.Text.Json.Utf8JsonReader.GetString()
   at System.Text.Json.Serialization.Converters.StringConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at MyTikTokBackup.Desktop.ViewModels.UserDataViewModel.ImportUserDataFile()
2022-04-10 11:15:07.983 -07:00 [INF] NavigationCompleted
2022-04-10 11:15:11.237 -07:00 [INF] QueueVideos items: 0, to download: 0 queue 0 _itemsToDownload 0
2022-04-10 11:15:15.261 -07:00 [ERR] Can't deserialize user data System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.Profile['Profile Information'].ProfileMap.PlatformInfo[0] | LineNumber: 561754 | BytePositionInLine: 11.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'StartObject' as a string.
   at System.Text.Json.Utf8JsonReader.GetString()
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at MyTikTokBackup.Desktop.ViewModels.UserDataViewModel.ImportUserDataFile()

**Comment by tmk907** [comment]
This release should fix it [https://github.com/tmk907/MyTikTokBackup/releases/download/v1.1.12/MyTikTokBackup.Desktop.Package._1.1.12.0_x64.msix](https://github.com/tmk907/MyTikTokBackup/releases/download/v1.1.12/MyTikTokBackup.Desktop.Package._1.1.12.0_x64.msix)

**Comment by zod-melodic** [comment]
It indeed seems to be fixed. Thank you!

Is there an option to download liked videos from JSON data?

**Comment by tmk907** [comment]
It is possible to do, but I didn't added that option. To make it work the application would need to find urls to download. And if it makes too many requests, TikTok returns captcha, which can't be automatically solved. The best way is to use built in browser.
