### ISSUE TITLE
Download from user_data.json doesnt work

### ISSUE THREAD

**Issue by Txxicer** [tmk907/MyTikTokBackup#6]
Hi,

If I import my user_data.json and click on "Download", nothing happens. Please fix it. Thanks.

**Comment by tmk907** [comment]
Please check if there are any errors [ERR] in logs in folder %LocalAppData%\Packages\60490polApki.MyTikTokBackup_4j2bpc236qkhp\LocalState

**Comment by Txxicer** [comment]
Yes, I get a few errors, almost the same:

`2023-01-17 17:58:05.313 +01:00 [ERR] System.NullReferenceException: Object reference not set to an instance of an object.
   at MyTikTokBackup.Desktop.ViewModels.UserDataViewModel.ImportUserDataFile()`

`Flurl.Http.FlurlHttpException: Call failed with status code 400 (Bad Request): GET https://www.tiktok.com/oembed?url=https://www.tiktok.com/share/video/7185096577768508718/
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
   at MyTikTokBackup.Desktop.ViewModels.UserDataViewModel.GetFinalUrl(String url, CancellationToken token)`

`2023-01-17 19:11:38.350 +01:00 [ERR] System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Nutzer\Freddy\Desktop\TTliked\@freshy_2005\Bookmarks'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.Directory.GetFiles(String path)
   at MyTikTokBackup.Desktop.ViewModels.UserDataViewModel.ExcludeAlreadyDownloadedVideos(IEnumerable`1 urls)
   at MyTikTokBackup.Desktop.ViewModels.UserDataViewModel.ImportUserDataFile()`

**Comment by tmk907** [comment]
Please check if it's fixed in new version https://github.com/tmk907/MyTikTokBackup/releases/tag/v1.1.14
You need only msix file to update application.

**Comment by Txxicer** [comment]
Thank you, now it works partly.

If I import the user_data.json it recognizes 8000 liked videos and 24 bookmarked videos but find only 4 urls and 4 bookmarked videos. But I want to download the liked videos. If I click on Download, it just downloads the 4 found bookmarked videos.

**Comment by tmk907** [comment]
You can't download liked videos using user_data.json. This is not a completely automatic process. You have to find your profile in browser, open 'Liked' tab and scroll page to find all videos (or press PgDn button). The best way is to look for and download videos in batches because if you close app downloads will not be resumed.

**Comment by Txxicer** [comment]
Oh okay, I see.

Thank you anyway.
